# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EventLogger' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EventLogger
  # Pods for test_google_signin
  pod 'GoogleSignIn'
  pod 'Firebase/Core'

  target 'EventLogger-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EventLoggerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

